### ISSUE TITLE
Remove index method on DeploymentConfigurationController

### ISSUE THREAD

**Issue by agileraymond** [agileraymond/DotNetDeployments#31]
I used this method to test my calls to AWS code deploy api. Now that everything is setup, we can delete it.

**Comment by MrClan** [comment]
I'm trying to get started with OSS, so I'm a little confused. Any pointers would be appreciated.
So, i've got 2 questions: 
1. all that this issue requires is to remove that *index* method ?
2. if we remove that, what should *AppNewSave* method return, as it returns *index* currently ?
Thanks.

**Comment by agileraymond** [comment]
AppNewSave method is currently not working so it's safe to remove index method. I'll create a new issue to fix AppNewSave method.

**Comment by MrClan** [comment]
Thanks. I've created a pull request for this issue.

**Comment by agileraymond** [comment]
@MrClan Thanks for your contribution.
