### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by agileraymond** [agileraymond/DotNetDeployments#7]
Add unit test framework that works with .NET Core 2.
Make sure #9 is completed before adding unit tests.

**Comment by KevinLamb** [comment]
I can build a basic unit testing project for you. Just assign it to me and I'll do a PR today/tomorrow.

**Comment by agileraymond** [comment]
Adding a reference on how to add unit test project, 
https://github.com/dotnet/docs/blob/master/docs/core/testing/unit-testing-with-dotnet-test.md

**Comment by KevinLamb** [comment]
Thanks, I'll start working on this in the evening.

**Comment by muhihsan** [comment]
@agileraymond unit test project added with some test scenarios for models here #17

**Comment by KevinLamb** [comment]
I'll add some tests on to it once it gets merged. Nice work @muhihsan
