### ISSUE TITLE
Add src folder to root

### ISSUE THREAD

**Issue by agileraymond** [agileraymond/DotNetDeployments#8]
Create src folder at the root level. Move current files to src folder. This will help us keep the project better organize.

**Comment by MarsMSJ** [comment]
Hello Raymond, I'm looking at the root level  directory and I only see the solution file. Is this the file you intended to move to the src folder? I don't see any other cs files. Did you mean to include the .vscode dir?

**Comment by agileraymond** [comment]
Create src folder at the same level as README.md file. After creating the src folder, move folder DotNetDeployments and its contents inside the src folder. Also move DotNetDeployments.sln inside src folder. That's it. Thanks.

**Comment by kennyhuynh125** [comment]
Hi Raymond, will be working on this!
