### ISSUE TITLE
Add tests folder to root 

### ISSUE THREAD

**Issue by agileraymond** [agileraymond/DotNetDeployments#9]
To keep the project organized, we need to add a tests folder to the root level. Inside this folder we will add unit tests.

**Comment by Demo318** [comment]
Just adding the folder? I think I can do that :-)

**Comment by agileraymond** [comment]
Go for it. Thanks for contributing.

**Comment by Demo318** [comment]
@agileraymond so this is a folder "tests" in the same directory as you'll find "wwwroot" "Model" "views" etc.? I don't want to put it in the wrong place...

**Comment by Demo318** [comment]
PR #10 https://github.com/agileraymond/DotNetDeployments/pull/10

**Comment by agileraymond** [comment]
No, place it in the same level as the readme.md file.

**Comment by iknoorjobs** [comment]
@agileraymond Issue Fixed. Kindly check.

**Comment by agileraymond** [comment]
@iknoorjobs Thanks for your contribution.
